-- Chat system schema. Hibernate runs with ddl-auto=validate, so these column names and
-- types must match the JPA entities exactly (snake_case columns, enums stored as VARCHAR).

CREATE TABLE users (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     VARCHAR(64)  NOT NULL UNIQUE,
    display_name VARCHAR(128),
    created_at   TIMESTAMPTZ  NOT NULL,
    updated_at   TIMESTAMPTZ  NOT NULL
);

CREATE TABLE conversations (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- ConversationType: ONE_TO_ONE | GROUP
    type       VARCHAR(16)  NOT NULL,
    name       VARCHAR(128),
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ  NOT NULL
);

CREATE TABLE conversation_members (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT      NOT NULL REFERENCES conversations (id),
    user_id         BIGINT      NOT NULL REFERENCES users (id),
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_conversation_member UNIQUE (conversation_id, user_id)
);

-- Fan-out target lookup: "who are the members of conversation X?"
CREATE INDEX idx_members_conversation ON conversation_members (conversation_id);
-- Reverse lookup: "which conversations is user Y in?"
CREATE INDEX idx_members_user ON conversation_members (user_id);

CREATE TABLE messages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT      NOT NULL REFERENCES conversations (id),
    sender_id       BIGINT      NOT NULL REFERENCES users (id),
    content         TEXT        NOT NULL,
    -- MessageStatus: SENT | DELIVERED | READ
    status          VARCHAR(16) NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL
);

-- Composite index that serves keyset pagination and offline catch-up:
-- WHERE conversation_id = ? AND id > ? ORDER BY id ASC.
CREATE INDEX idx_messages_conversation_id ON messages (conversation_id, id);

-- Transactional outbox: message events are written here in the same tx as the message
-- insert, then relayed to Kafka by OutboxPoller.
CREATE TABLE outbox_events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_id VARCHAR(64)  NOT NULL,
    event_type   VARCHAR(64)  NOT NULL,
    payload      TEXT         NOT NULL,
    published    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMPTZ  NOT NULL,
    published_at TIMESTAMPTZ
);

-- The poller scans for unpublished rows oldest-first; a partial index keeps that cheap
-- as published rows accumulate.
CREATE INDEX idx_outbox_unpublished ON outbox_events (created_at)
    WHERE published = FALSE;
